service:
  name: product-service
  profile: pesonal
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SNS_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Action:
        - "sns:*"
      Effect: "Allow"
      Resource:
        Ref: SNSTopic

functions:
  getProductsById:
    handler: handlers/getProductsById.handler
    events:
      - http:
          method: get
          path: products/{id}
          cors: true
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - http:
          method: get
          path: products
          cors: true
  createProduct:
    handler: handlers/createProduct.handler
    events:
      - http:
          method: post
          path: products
          cors: true
  catalogBatchProcess:
    handler: handlers/catalog-batch-process.handler
    events:
      - sqs:
          batchSize: 5
          arn:
            '${cf:import-service-be-33-${self:provider.stage}.SQSQueueArn}'

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: rs-product-topic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:EMAIL}
        FilterPolicy:
          numOfProducts:
            - numeric:
                - "<"
                - 2
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    ExtraSnsSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:EXTRA_EMAIL}
        FilterPolicy:
          numOfProducts:
            - numeric:
                - ">="
                - 2
        Protocol: email
        TopicArn:
          Ref: SNSTopic
