service:
  name: import-service

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  profile: pesonal

  environment:
    S3_BUCKET_NAME: az-import-bucket
    S3_PARSED_PREFIX: parsed/
    S3_REGION: eu-west-1
    S3_UPLOADED_PREFIX: uploaded/

  iamRoleStatements:
    - Action:
        - s3:ListBucket
      Effect: Allow
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}
    - Action:
        - s3:*
      Effect: Allow
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*

plugins:
  - serverless-plugin-webpack

functions:
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:provider.environment.S3_UPLOADED_PREFIX}
          existing: true
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
