service:
  name: import-service
  profile: pesonal

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:provider.environment.S3_REGION}
  stage: ${opt:stage, 'dev'}

  environment:
    S3_BUCKET_NAME: az-import-bucket-be
    S3_REGION: eu-west-1

  iamRoleStatements:
    - Action:
        - "s3:ListBucket"
      Effect: "Allow"
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}
    - Action:
        - "s3:*"
      Effect: "Allow"
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
